# Generated by Django 4.2 on 2025-01-09 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "testplans",
            "0002_testplan_chatroom_testplan_plan_id_alter_testplan_id_and_more",
        ),
        ("progress", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="progressstatus",
            name="id",
        ),
        migrations.AddField(
            model_name="progressstatus",
            name="status_id",
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="progressstatus",
            name="plan_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress",
                to="testplans.testplan",
            ),
        ),
    ]
