# Generated by Django 4.2 on 2025-01-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_gender_user_phone_user_profile_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
