# Generated by Django 4.2 on 2025-01-07 12:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testplans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='메시지 내용')),
                ('message_style', models.CharField(choices=[('GENTLE', '상냥한'), ('STRICT', '팩폭'), ('FORMAL', '딱딱한'), ('FUN', '재미있는')], max_length=10, verbose_name='메시지 스타일')),
            ],
        ),
        migrations.CreateModel(
            name='ReminderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_start_hour', models.IntegerField(default=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='학습 시작 시간')),
                ('study_end_hour', models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='학습 종료 시간')),
                ('reminder_interval', models.CharField(choices=[('NONE', '알림 없음'), ('HOURLY_1', '1시간 마다'), ('HOURLY_2', '2시간 마다'), ('HOURLY_3', '3시간 마다')], default='NONE', max_length=10, verbose_name='알림 간격')),
                ('message_style', models.CharField(choices=[('GENTLE', '상냥한'), ('STRICT', '팩폭'), ('FORMAL', '딱딱한'), ('FUN', '재미있는')], default='GENTLE', max_length=10, verbose_name='메시지 스타일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_settings', to='testplans.testplan')),
            ],
        ),
    ]
