# Generated by Django 4.2 on 2025-01-14 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagetemplate',
            name='created_at',
        ),
    ]
