# Generated by Django 4.2 on 2025-01-17 21:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remindersetting',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='remindersetting',
            name='start_time',
        ),
        migrations.AddField(
            model_name='remindersetting',
            name='end_hour',
            field=models.IntegerField(default=18, help_text='종료 시간 (0-23)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remindersetting',
            name='end_minute',
            field=models.IntegerField(default=0, help_text='종료 분 (0-59)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remindersetting',
            name='start_hour',
            field=models.IntegerField(default=9, help_text='시작 시간 (0-23)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remindersetting',
            name='start_minute',
            field=models.IntegerField(default=0, help_text='시작 분 (0-59)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
            preserve_default=False,
        ),
    ]
