# Generated by Django 4.2 on 2025-01-06 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remindersettings',
            old_name='plan',
            new_name='test_plan',
        ),
        migrations.RemoveField(
            model_name='remindersettings',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='remindersettings',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminder_settings', to='reminder.remindertemplate'),
        ),
        migrations.AlterField(
            model_name='remindersettings',
            name='study_start_time',
            field=models.TimeField(default='09:00', verbose_name='학습 시작 시간'),
        ),
        migrations.AlterModelTable(
            name='remindersettings',
            table=None,
        ),
        migrations.AlterModelTable(
            name='remindertemplate',
            table=None,
        ),
    ]
