# Generated by Django 4.2 on 2025-01-09 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chatrooms", "0004_alter_chatroom_testplan"),
        ("testplans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testplan",
            name="chatroom",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linked_testplan",
                to="chatrooms.chatroom",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="testplan",
            name="plan_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testplan",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name="testplan",
            unique_together={("plan_id", "chatroom")},
        ),
    ]
