# Generated by Django 4.2 on 2025-01-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "testplans",
            "0002_testplan_chatroom_testplan_plan_id_alter_testplan_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="testplan",
            name="on_progress",
            field=models.BooleanField(default=1),
        ),
    ]
