# Generated by Django 4.2 on 2025-01-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testplans", "0003_testplan_on_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="testplan",
            name="test_plan",
            field=models.JSONField(null=True),
        ),
    ]
