# Generated by Django 4.2 on 2025-01-06 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatrooms", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatroom",
            name="plan_id",
        ),
    ]
