# Generated by Django 4.2 on 2025-01-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatrooms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="message_id",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
