# Generated by Django 4.2 on 2025-01-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatrooms", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="chatroom_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
