# Generated by Django 4.2 on 2025-01-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatrooms", "0002_alter_chatmessage_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="message_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
