# Generated by Django 4.2 on 2025-01-07 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chatrooms", "0002_remove_chatroom_plan_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("message_id", models.AutoField(primary_key=True, serialize=False)),
                ("message_content", models.JSONField()),
                (
                    "sent_by",
                    models.CharField(
                        choices=[("user", "User"), ("ai", "AI")], max_length=20
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chat_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chatmessages",
                        to="chatrooms.chatroom",
                    ),
                ),
            ],
        ),
    ]
