# Generated by Django 4.2 on 2025-01-09 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("testplans", "0001_initial"),
        ("chatrooms", "0003_alter_chatmessage_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="testplan",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_chatroom",
                to="testplans.testplan",
            ),
        ),
    ]
